services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "55678:5678"
    volumes:
      - n8n_auth_data:/home/node/.n8n
      - D:/shared/rag:/data/shared
    environment:
      - GENERIC_TIMEZONE=UTC
      - N8N_RUNNERS_ENABLED=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    restart: always
    
  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    container_name: postgres-vector
    ports:
      - "55432:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
    environment:
      POSTGRES_DB: authdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always

  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    volumes:
      - ollama:/root/.ollama
    ports:
      - "51434:11434"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 16G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
    
volumes:
  pg_auth_data:
  n8n_auth_data:
  ollama:
    driver: local